version: '3'

services:

  mongo:
    image: mongo:3
    container_name: envoice-mongorepository
    command: mongod --smallfiles --bind_ip_all
    ports:
      - "27017:27017"
    networks:
      - dev-network
    tty: true
    stdin_open: true

networks:
  dev-network:
    driver: bridge
